# global-radio 加速缓存 http 级配置（注入 server{ 之前，勿手改）
proxy_cache_path /var/cache/nginx/graccel_api levels=1:2 keys_zone=graccel_api:8m  max_size=64m  inactive=2h  use_temp_path=off;
proxy_cache_path /var/cache/nginx/graccel_img levels=1:2 keys_zone=graccel_img:20m max_size=1g   inactive=30d use_temp_path=off;
