#!/bin/bash
### Main lifecycle script for Docker-based fpk app.

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    local DOCKER_NAME=""
    if [ -f "$FILE_PATH" ]; then
        DOCKER_NAME="$(grep "container_name" "$FILE_PATH" | awk -F ':' '{print $2}' | xargs)"
    fi
    if [ -n "$DOCKER_NAME" ]; then
        docker inspect "$DOCKER_NAME" >/dev/null 2>&1 || return 1
        docker inspect "$DOCKER_NAME" | grep -q '"Status": "running"' || return 1
        return 0
    fi
    return 1
}

case $1 in
start)
    exit 0
    ;;
stop)
    exit 0
    ;;
status)
    if is_docker_running; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
